# Generated by Django 3.0 on 2019-12-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('lecture_time', models.DateTimeField()),
                ('introduction', models.TextField(blank=True)),
                ('capacity', models.IntegerField()),
                ('lecture_location', models.TextField()),
                ('lecturer', models.TextField()),
                ('lecturer_introduction', models.TextField()),
            ],
        ),
    ]
