# Generated by Django 3.0 on 2020-02-08 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('lecture_time', models.DateTimeField()),
                ('introduction', models.TextField(blank=True)),
                ('capacity', models.IntegerField()),
                ('lecture_location', models.TextField()),
                ('lecturer', models.TextField()),
                ('lecturer_introduction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DrawResult',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('draw_status', models.CharField(choices=[('PEN', 'Pending'), ('WIN', 'Win'), ('MIS', 'Missed')], default='PEN', max_length=3)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('didAttend', models.BooleanField(default=False, verbose_name='Attendance')),
                ('lecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
