# Generated by Django 3.0 on 2019-12-07 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_staus', models.CharField(choices=[('PEN', 'Pending'), ('WIN', 'Win'), ('MIS', 'Missed')], default='PEN', max_length=3)),
                ('lecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('didAttend', models.BooleanField(default=False, verbose_name='Attendance')),
                ('lecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
